<a href="https://colab.research.google.com/github/abhishekbhat11/DSML/blob/main/Task1_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('IRIS.csv')

In [ ]:
data.index

RangeIndex(start=0, stop=150, step=1)

In [ ]:
data.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [ ]:
data.tail(10)

     sepal_length  sepal_width  petal_length  petal_width         species
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
data.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
dtype: float64

In [ ]:
data.median()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64

In [ ]:
data.sort_values(by='sepal_length',ascending=False)

     sepal_length  sepal_width  petal_length  petal_width         species
131           7.9          3.8           6.4          2.0  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
..            ...          ...           ...          ...             ...
41            4.5          2.3           1.3          0.3     Iris-setosa
42            4.4          3.2           1.3          0.2     Iris-setosa
38            4.4          3.0           1.3          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa

[150 rows x 5 columns]

In [ ]:
data.sort_values(by='sepal_width',ascending=False)

     sepal_length  sepal_width  petal_length  petal_width          species
15            5.7          4.4           1.5          0.4      Iris-setosa
33            5.5          4.2           1.4          0.2      Iris-setosa
32            5.2          4.1           1.5          0.1      Iris-setosa
14            5.8          4.0           1.2          0.2      Iris-setosa
16            5.4          3.9           1.3          0.4      Iris-setosa
..            ...          ...           ...          ...              ...
87            6.3          2.3           4.4          1.3  Iris-versicolor
62            6.0          2.2           4.0          1.0  Iris-versicolor
68            6.2          2.2           4.5          1.5  Iris-versicolor
119           6.0          2.2           5.0          1.5   Iris-virginica
60            5.0          2.0           3.5          1.0  Iris-versicolor

[150 rows x 5 columns]

In [ ]:
data.sort_values(by='petal_length',ascending=False)

     sepal_length  sepal_width  petal_length  petal_width         species
118           7.7          2.6           6.9          2.3  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
105           7.6          3.0           6.6          2.1  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
..            ...          ...           ...          ...             ...
36            5.5          3.5           1.3          0.2     Iris-setosa
35            5.0          3.2           1.2          0.2     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa
22            4.6          3.6           1.0          0.2     Iris-setosa

[150 rows x 5 columns]

In [ ]:
data.sort_values(by='petal_width',ascending=False)

     sepal_length  sepal_width  petal_length  petal_width         species
100           6.3          3.3           6.0          2.5  Iris-virginica
109           7.2          3.6           6.1          2.5  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
114           5.8          2.8           5.1          2.4  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
..            ...          ...           ...          ...             ...
13            4.3          3.0           1.1          0.1     Iris-setosa
37            4.9          3.1           1.5          0.1     Iris-setosa
32            5.2          4.1           1.5          0.1     Iris-setosa
34            4.9          3.1           1.5          0.1     Iris-setosa
9             4.9          3.1           1.5          0.1     Iris-setosa

[150 rows x 5 columns]

In [ ]:
data.isnull()

     sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [ ]:
df=data.copy()
df.dropna()

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]